name: Deploy aws lambda 

on:
  push:
    branches:
      - main 
    paths:
      - 'lambda/**'

jobs:
  deploy-lambda: #name of our job
    runs-on: ubuntu-latest #set the runner

    steps:
      - uses: actions/checkout@v2

    
      - name: Set up Python  #Set up out python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install dependencies  #Installs any packages 
        run: |
          python -m pip install --upgrade pip
          pip install -r lambda/requirements.txt -t lambda/

      - name: Configure AWS creds #set up aws cred
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: us-west-1

      - name: Deploy lambda Function #Zips Lambda Directory and update lamb function
        run: |
          cd lambda
          zip -r lambda.zip .
          aws lambda update-function-code --function-name my-test-cicd --zip-file file://lambda.zip



